dist: bionic

language: node_js

matrix:
  fast_finish: true

  include:
    - node_js: lts/*
      env: DEPLOY=true
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/bjorkfr
        keep_history: true
        on:
          branch: master

    - node_js: node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn lint
  - yarn audit
  - yarn test
  - yarn e2e
  - if [[ $DEPLOY = 'true' ]]; then yarn build --prod; fi
